name: Update HackerRank Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:     # Manual test

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate HackerRank Stats
        uses: athul/hackerrank-readme-stats@master
        with:
          username: rkbhd88
          theme: dark 

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update HackerRank stats" || echo "No changes to commit"
          git push